# frozen_string_literal: true

require_relative 'config/application'

Rails.application.load_tasks

task :test do
  Dir
    .glob('test/**/*_test.rb')
    .reject { |f| f.include?('e2e') }
    .sort
    .each { |f| require_relative f }
end

desc 'Run e2e tests'
task :e2e do
  # Disconnect AR so forked subprocess doesn't inherit stale SQLite FDs
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.connection_handler.clear_all_connections!
  end
  sh('ruby', 'test/e2e_test.rb')
end

task default: %i[test e2e]
