#!/usr/bin/env ruby
# frozen_string_literal: true

unless ENV['RUBY_BOX'] == '1'
  puts "Error: Boxwerk requires Ruby::Box to be enabled"
  puts "Please set RUBY_BOX=1 environment variable"
  exit 1
end

unless defined?(Ruby::Box)
  puts "Error: Ruby::Box is not available in this Ruby version"
  puts "Boxwerk requires Ruby 4.0 or later with Box support"
  exit 1
end

Ruby::Box.root.eval(<<~RUBY)
  require 'bundler/setup'
  Bundler.require
  Boxwerk::CLI.run(ARGV)
RUBY
