name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.1"
      - name: Install development dependencies
        run: bundle install
      - name: Generate RDoc
        run: rdoc --markup markdown --main README.md --exclude 'box_manager|setup|cli|constant_resolver|gem_resolver|package_resolver|privacy_checker|zeitwerk_scanner|gemfile_require_parser' lib/ README.md CHANGELOG.md USAGE.md
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
